services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    restart: unless-stopped
    ports:
      - '9100:9100'
    environment:
      # WEBHOOK_EVENTS_TAKEN: "LOGIN,REGISTER,LOGOUT"

      WEBHOOK_HTTP_BASE_PATH: "http://prism:4010"
      WEBHOOK_HTTP_AUTH_USERNAME: "admin"
      WEBHOOK_HTTP_AUTH_PASSWORD: "password"

      WEBHOOK_AMQP_HOST: rabbitmq
      WEBHOOK_AMQP_USERNAME: username
      WEBHOOK_AMQP_PASSWORD: password
      WEBHOOK_AMQP_PORT: 5672
      WEBHOOK_AMQP_EXCHANGE: keycloak
      WEBHOOK_AMQP_VHOST: "/"

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password

      KC_HTTP_PORT: 9100
      KC_METRICS_ENABLED: 'true'
      KC_LOG_CONSOLE_COLOR: 'true'
      KC_HEALTH_ENABLED: 'true'
    entrypoint: /bin/sh
    command:
      - -c
      - |
        set -ex
        cp /tmp/libs/*-all.jar /opt/keycloak/providers

        /opt/keycloak/bin/kc.sh build
        /opt/keycloak/bin/kc.sh start-dev --import-realm

    volumes:
      - ./.docker/keycloak-config/:/opt/keycloak/data/import/:ro
      - ./build/libs:/tmp/libs:ro
    links:
      - prism

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password

  # This is a mock server for the SMS API
  prism:
    image: stoplight/prism:latest
    ports:
      - '4010:4010'
    command:
      - mock
      - -h
      - 0.0.0.0
      - /webhook.open-api.yml
    volumes:
      - ./openapi/webhook.open-api.yml:/webhook.open-api.yml

