name: Build

on:
  push:
    branches: [ main, add-nats-provider ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Shadow JARs
      run: ./gradlew shadowJar
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: keycloak-webhook-jars
        path: |
          **/build/libs/*-all.jar